### ISSUE TITLE
Do you have any lab for the hot path in the architecture?

### ISSUE THREAD

**Issue by davidaascorreia** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#56]
Do you have any lab for the hot path in the architecture? Can't seem to find it in this repository.

**Comment by codingbandit** [comment]
Hi David, as mentioned in the Solution architecture section - this lab focuses on the cold path scenario in order to get familiar with Azure Synapse Analytics Workspace. You can explore the [Whiteboard design session](https://github.com/microsoft/MCW-Azure-Synapse-Analytics-and-AI/tree/master/Whiteboard%20design%20session) to learn more about the recommended hot path architecture and related services.

**Comment by davidaascorreia** [comment]
Ok, thanks!
