### ISSUE TITLE
Exercise 5 - Running indexer

### ISSUE THREAD

**Issue by ekuipers** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#59]
Although the indexer was created successfully, it didn't find any projections in the PDF file like for example customer ID or product ID.

Could not generate projection from input '/document'. Check the 'source' or 'sourceContext' property of your projection in your skillset. =$(/document) ?map { "customerid": $(/document/formrecognizer/analyzeResult/readResults/0/lines/11/words/0/text), "filename": $(/document/metadata_storage_name), "productid": $(/document/formrecognizer/analyzeResult/readResults/0/lines/16/words/0/text), "productprice": $(/document/formrecognizer/analyzeResult/readResults/0/lines/17/words/0/text), "quantity": $(/document/formrecognizer/analyzeResult/readResults/0/lines/18/words/0/text), "totalcharges": $(/document/formrecognizer/analyzeResult/readResults/0/lines/19/words/0/text), "transactionid":

**Comment by codingbandit** [comment]
I will look into this, thank you @ekuipers !

**Comment by codingbandit** [comment]
Luckily I remembered recording exercise 5 for another issue. Could you perform exercise 5 following the steps and referring to the video here (https://www.dropbox.com/s/ulukbiytx75fw46/SynapseMCWIssue55.mp4?dl=0). Some of the common errors are due to files not being in the correct location. **if you could remove all created assets from exercise 5**, and I will outline a few things to look for at certain steps.  please delete the form recognizer service, the search service, and the azure function/resource group entirely.

Areas to look out for:

Task 1, steps 6-11. We have seen in the past some browsers be finicky with the Storage Explorer. Please verify that the invoices container has a Test and Train folder. The Test folder will have invoices 6 and 7, and the Train folder should have invoices 1 through 5.

Task 1, step 15. Give your SAS token a longer duration by increasing the end date, sometimes the lab isn't completed in one sitting and the SAS URL can expire.

Task 1, step 17, This is one that seems to get overlooked from time to time, ensure you inject the text "invoices" to the SAS url that was created (before the ? character)

Task 2, step 16, be sure to use the Form Recognizer service secrets (not the cognitive search)

Task 2, step 20, When this runs, it shouldn't return immediately, please make sure in the text directly above the output of the model that you see the text that "Training succeeded" and next to the modelId that the status is "ready" -- if something goes wrong in the training it will not succeed and show a status of invalid, but still output a modelId.

Other than that, in Postman for the variables, just be sure to pay attention if the variable is requesting the Form recognizer service secrets or the cognitive search service.

I also want you to know that not finishing this exercise does not stop you from jumping to the next exercise in this lab. So if you want to come back to it later, there is no ill effects from skipping it for now.

**Comment by ekuipers** [comment]
thx for the suggestions, I'll try this out.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as no further remarks.  Please reopen if needed
